module.exports = {
    content: ["./src/**/*.{tsx,ts}"],
    theme: {
        colors: {
            primary: "var(--primary)",
            onPrimary: "var(--onPrimary)",
            primaryContainer: "var(--primaryContainer)",
            onPrimaryContainer: "var(--onPrimaryContainer)",
            secondary: "var(--secondary)",
            onSecondary: "var(--onSecondary)",
            secondaryContainer: "var(--secondaryContainer)",
            onSecondaryContainer: "var(--onSecondaryContainer)",
            tertiary: "var(--tertiary)",
            onTertiary: "var(--onTertiary)",
            tertiaryContainer: "var(--tertiaryContainer)",
            onTertiaryContainer: "var(--onTertiaryContainer)",
            error: "var(--error)",
            errorContainer: "var(--errorContainer)",
            onError: "var(--onError)",
            onErrorContainer: "var(--onErrorContainer)",
            background: "var(--background)",
            onBackground: "var(--onBackground)",
            surface: "var(--surface)",
            onSurface: "var(--onSurface)",
            surfaceVariant: "var(--surfaceVariant)",
            onSurfaceVariant: "var(--onSurfaceVariant)",
            outline: "var(--outline)",
            inverseOnSurface: "var(--inverseOnSurface)",
            inverseSurface: "var(--inverseSurface)",
            tranparent: "transparent",
        },
        extend: {
            boxShadow: {
                borderPrimary: "0 0 0 4px var(--onPrimaryContainer)",
                borderSecondary: "0 0 0 4px var(--onSecondaryContainer)",
                borderTertiary: "0 0 0 4px var(--onTertiaryContainer)",
                borderError: "0 0 0 4px var(--onErrorContainer)",
            },
        },
    },
    plugins: [],
    corePlugins: {
        preflight: false,
    },
};
