module.exports = {
    content: ["./src/**/*.{tsx,ts}"],
    theme: {
        colors: {
            primary: "var(--primary)",
            onPrimary: "var(--onPrimary)",
            primaryContainer: "var(--primaryContainer)",
            onPrimaryContainer: "var(--onPrimaryContainer)",
            secondary: "var(--secondary)",
            onSecondary: "var(--onSecondary)",
            secondaryContainer: "var(--secondaryContainer)",
            onSecondaryContainer: "var(--onSecondaryContainer)",
            tertiary: "var(--tertiary)",
            onTertiary: "var(--onTertiary)",
            tertiaryContainer: "var(--tertiaryContainer)",
            onTertiaryContainer: "var(--onTertiaryContainer)",
            error: "var(--error)",
            errorContainer: "var(--errorContainer)",
            onError: "var(--onError)",
            onErrorContainer: "var(--onErrorContainer)",
            background: "var(--background)",
            onBackground: "var(--onBackground)",
            surface: "var(--surface)",
            onSurface: "var(--onSurface)",
            surfaceVariant: "var(--surfaceVariant)",
            onSurfaceVariant: "var(--onSurfaceVariant)",
            outline: "var(--outline)",
            inverseOnSurface: "var(--inverseOnSurface)",
            inverseSurface: "var(--inverseSurface)",
            tranparent: "transparent",
            disabled: "var(--disabled)",
        },
        boxShadow: {
            elevation1: "var(--elevation1)",
            elevation2: "var(--elevation2)",
            elevation3: "var(--elevation3)",
            elevation4: "var(--elevation4)",
            elevation5: "var(--elevation5)",
            none: "none",
        },
        fontSize: {
            displayLarge: ["57px", "64px"],
            displayMedium: ["45px", "52px"],
            displaySmall: ["36px", "44px"],
            headlineLarge: ["32px", "40px"],
            headlineMedium: ["28px", "36px"],
            headlineSmall: ["24px", "32px"],
            titleLarge: ["22px", "28px"],
            titleMedium: [
                "16px",
                { lineHeight: "24px", letterSpacing: "0.15px" },
            ],
            titleSmall: [
                "14px",
                { lineHeight: "20px", letterSpacing: "0.1px" },
            ],
            labelLarge: [
                "14px",
                { letterSpacing: "0.1px", lineHeight: "20px" },
            ],
            labelMedium: [
                "12px",
                { letterSpacing: "0.5px", lineHeight: "16px" },
            ],
            labelSmall: [
                "11px",
                { letterSpacing: "0.5px", lineHeight: "16px" },
            ],
            bodyLarge: [
                "16px",
                { letterSpacing: "0.15px", lineHeight: "24px" },
            ],
            bodyMedium: [
                "14px",
                { letterSpacing: "0.25px", lineHeight: "20px" },
            ],
            bodySmall: ["12px", { letterSpacing: "0.4px", lineHeight: "16px" }],
        },
        borderRadius: {
            DEFAULT: "100px",
        },
        fontFamily: {
            sans: ["Roboto", "sans-serif"],
        },
    },
    plugins: [],
    corePlugins: {
        preflight: false,
    },
};
